apiVersion: v1
kind: Service
metadata:
  name: {{ include "drive-clone.fullname" . }}-minio
spec:
  ports:
    - port: 9000
  selector:
    app: {{ include "drive-clone.fullname" . }}-minio

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "drive-clone.fullname" . }}-minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "drive-clone.fullname" . }}-minio
  template:
    metadata:
      labels:
        app: {{ include "drive-clone.fullname" . }}-minio
    spec:
      containers:
        - name: minio
          image: minio/minio:latest
          args: ["server", "/data", "--console-address", ":9001"]
          env:
            - name: MINIO_ROOT_USER
              value: "minioadmin"
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "drive-clone.fullname" . }}-secrets
                  key: minioRootPassword
          ports:
            - containerPort: 9000
            - containerPort: 9001
          volumeMounts:
            - name: minio-data
              mountPath: /data
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: {{ include "drive-clone.fullname" . }}-minio-pvc
