apiVersion: v1
kind: Service
metadata:
  name: {{ include "drive-clone.fullname" . }}-postgres
spec:
  ports:
    - port: 5432
  selector:
    app: {{ include "drive-clone.fullname" . }}-postgres

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "drive-clone.fullname" . }}-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "drive-clone.fullname" . }}-postgres
  template:
    metadata:
      labels:
        app: {{ include "drive-clone.fullname" . }}-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: "drive"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "drive-clone.fullname" . }}-secrets
                  key: postgresPassword
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ include "drive-clone.fullname" . }}-postgres-pvc
