apiVersion: v1
kind: Secret
metadata:
  name: {{ include "drive-clone.fullname" . }}-secrets
type: Opaque
data:
  postgresPassword: {{ .Values.secrets.postgresPassword | b64enc }}
  minioRootPassword: {{ .Values.secrets.minioRootPassword | b64enc }}
