replicaCount: 1

image:
  repository: drive-clone
  tag: latest

service:
  type: ClusterIP
  port: 80

env:
  DATABASE_URL: "postgresql://postgres:postgres@db:5432/drive"
  MINIO_ENDPOINT: "http://minio:9000"

resources:
  app:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

persistence:
  postgres:
    enabled: true
    size: 1Gi
  minio:
    enabled: true
    size: 5Gi

secrets:
  postgresPassword: postgres
  minioRootPassword: minioadmin
  MINIO_ENDPOINT: "http://minio:9000"
